# Q3. Singular Value Decomposition (SVD):
Perform Singular Value Decomposition on the matrix A obtained in Question 2. Separate and print matrices U, Σ, and 𝑉 ் . Verify that A equals the product of U, Σ, and 𝑉 ் . Additionally, find the rank 2 and rank 3 approximations of matrix A.

 

In [6]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
A = np.random.randint(0, 10, size=(5, 5))
print("Original matrix A:")
print(A)

Original matrix A:
[[5 7 7 4 1]
 [6 6 9 4 6]
 [1 8 0 6 7]
 [5 6 5 1 8]
 [8 7 7 0 8]]


In [8]:
#Q 3
# Perform Singular Value Decomposition (SVD)
U, Sigma, V_transpose = np.linalg.svd(A)
Sigma_mat = np.zeros_like(A, dtype=float)
Sigma_mat[:min(A.shape[0], A.shape[1]), :min(A.shape[0], A.shape[1])] = np.diag(Sigma)
print("Matrix U:")
print(U)
print("\nMatrix Sigma:")
print(Sigma_mat)
print("\nMatrix V:")
print(V_transpose.T) 

Matrix U:
[[-0.38831253  0.20646633  0.73047983  0.46617179 -0.23594091]
 [-0.50911834  0.22605058  0.22576441 -0.7704591   0.21242143]
 [-0.34775224 -0.91345816  0.10447885  0.04172747  0.178901  ]
 [-0.43543666 -0.0406215  -0.43104063 -0.06730372 -0.78639621]
 [-0.52865413  0.26498468 -0.46767275  0.42755779  0.49878298]]

Matrix Sigma:
[[27.47425757  0.          0.          0.          0.        ]
 [ 0.          8.35540477  0.          0.          0.        ]
 [ 0.          0.          6.39838869  0.          0.        ]
 [ 0.          0.          0.          2.49060332  0.        ]
 [ 0.          0.          0.          0.          0.45814756]]

Matrix V:
[[-0.42768913  0.40595842 -0.122706    0.33476851  0.72467444]
 [-0.54116529 -0.34647438  0.22565417  0.62769927 -0.37705365]
 [-0.47964954  0.61415395  0.26824349 -0.40734845 -0.39352753]
 [-0.22245091 -0.45375453  0.62840969 -0.41519584  0.42111292]
 [-0.49464538 -0.36342126 -0.68349845 -0.39446587 -0.02185139]]
